### ISSUE TITLE
some errors about the demo 

### ISSUE THREAD

**Issue by K0923** [NathanUA/U-2-Net#105]
cuda 9.0 cudnn 7.1.4 torch 0.4.1
----------------------------------------
Number of images:  11
inferencing  0 / 11 ./test_data/test_portrait_images/your_portrait_im\GalGadot.jpg
Traceback (most recent call last):
  File ".\u2net_portrait_demo.py", line 200, in <module>
    main()
  File ".\u2net_portrait_demo.py", line 194, in main
    im_portrait = inference(net,im_face)
  File ".\u2net_portrait_demo.py", line 126, in inference
    d1,d2,d3,d4,d5,d6,d7= net(tmpImg)
  File "C:\ProgramData\Anaconda3\envs\U-2-Net\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\zhang\PycharmProjects\U-2-Net-master\model\u2net.py", line 362, in forward
    hx1 = self.stage1(hx)
  File "C:\ProgramData\Anaconda3\envs\U-2-Net\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\zhang\PycharmProjects\U-2-Net-master\model\u2net.py", line 66, in forward
    hxin = self.rebnconvin(hx)
  File "C:\ProgramData\Anaconda3\envs\U-2-Net\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\zhang\PycharmProjects\U-2-Net-master\model\u2net.py", line 17, in forward
    xout = self.relu_s1(self.bn_s1(self.conv_s1(hx)))
  File "C:\ProgramData\Anaconda3\envs\U-2-Net\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\U-2-Net\lib\site-packages\torch\nn\modules\conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CuDNN error: CUDNN_STATUS_SUCCESS

**Comment by NathanUA** [comment]
I guess you are running on windows. We didn’t test the code on windows. But there are following suggestions:

(1) make sure the code loads the image correctly, "./test_data/test_portrait_images/your_portrait_im\GalGadot.jpg”.  Because the path separation between ubuntus (uses “/“)  and windows (use “\”)  is different.

(2) If the images can be loaded correctly, but the problem is still in ****_demo.py. Pls try to run the test.py to see if the problem is still there. If yes, then you may have to check if your pytorch version is compatible with the cudnn and cuda version. I tested the code on pytorch 0.4.0 and 1.4.0. Both works fine. Some others reported that pytorch 1.6.0 also works fine. My CUDA version is 10.2.

Best of luck.
