### ISSUE TITLE
IndexError: invalid index of a 0-dim tensor

### ISSUE THREAD

**Issue by muhammadabdullah34907** [NathanUA/U-2-Net#40]
python3 u2net_train.py

Traceback (most recent call last):
  File "u2net_train.py", line 140, in <module>
    loss2, loss = muti_bce_loss_fusion(d0, d1, d2, d3, d4, d5, d6, labels_v)
  File "u2net_train.py", line 40, in muti_bce_loss_fusion
    print("l0: %3f, l1: %3f, l2: %3f, l3: %3f, l4: %3f, l5: %3f, l6: %3f\n"%(loss0.data[0],loss1.data[0],loss2.data[0],loss3.data[0],loss4.data[0],loss5.data[0],loss6.data[0]))
IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number

**Comment by muhammadabdullah34907** [comment]
solved from this: 
https://github.com/pytorch/pytorch/issues/15585
